[package]
name = "i_shape_js"
version = "0.7.1"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "Boolean Operations for 2D Polygons. Supported operations: intersection, union, difference, XOR, and self-intersections for all polygon varieties."
license = "MIT"
repository = "https://github.com/iShape-Rust/iShape-js"

[lib]
crate-type = ["cdylib"]


[dependencies]
i_float = "1.0.1"
i_shape = "1.0.1"
i_overlay = "1.0.1"

#i_float = { path = "../iFloat" }
#i_shape = { path = "../iShape" }
#i_overlay = { path = "../iOverlay" }


wasm-bindgen = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde-wasm-bindgen = "^0.6"