[package]
name = "ishape_wasm"
version = "1.0.3"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "Boolean Operations for 2D Polygons. Supported operations: intersection, union, difference, XOR, and self-intersections for all polygon varieties."
license = "MIT"
repository = "https://github.com/iShape-Rust/iShape-js"

[lib]
crate-type = ["cdylib"]

[dependencies]
i_overlay = "~1.4.3"

wasm-bindgen = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde-wasm-bindgen = "^0.6"